version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: test-postgres
      POSTGRES_USER: test-postgres
      POSTGRES_DB: simpleBank
    volumes:
      - ./src/database/pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
  app:
    container_name: simpleBank-api
    restart: always
    build: .
    ports:
      - 3001:3001
    depends_on: 
      - db